### ISSUE TITLE
Cannot get size from a render object that has not been through layout.

### ISSUE THREAD

**Issue by fuadmostafij6** [railson-ferreira/scrollable_list_tab_scroller#12]
Column(
            children: [
              ScrollableListTabScroller(
                itemCount: tabData.length,
                // headerContainerBuilder: (context, widget)=>Text("Header"),
                tabBuilder: (BuildContext context, int index, bool active) => Padding(
                  padding: EdgeInsets.symmetric(horizontal: 10),
                  child: Text(
                    tabData.keys.elementAt(index),
                    style: !active
                        ? null
                        : TextStyle(fontWeight: FontWeight.bold, color: Colors.green),
                  ),
                ),
                itemBuilder: (BuildContext context, int index) => Column(
                  children: [
                    Text(
                      tabData.keys.elementAt(index),
                      style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20),
                    ),
                    ...tabData.values
                        .elementAt(index)
                        .asMap()
                        .map(
                          (index, value) => MapEntry(
                        index,
                        value
                      ),
                    )
                        .values
                  ],
                ),
              ),
            ],
          );
         
 when I wrap ScrollableListTabScroller with a Column, its show error

**Comment by railson-ferreira** [comment]
This is not a problem with this library. In order to use lists inside Column you may use Expanded, although there are other approaches you could try.

E.g.
```dart
Column(
  children: [
    Expanded(
      child: ScrollableListTabScroller
```
