### ISSUE TITLE
Package Error

### ISSUE THREAD

**Issue by xykadra** [railson-ferreira/scrollable_list_tab_scroller#14]
After installing the package into the project, the following error was displayed, preventing the application from building successfully again.
<img width="701" alt="image" src="https://github.com/railson-ferreira/scrollable_list_tab_scroller/assets/83673916/116391b9-4e62-4b48-914e-e47f78b9415b">

**Comment by xykadra** [comment]
After adding this line on line number 393 issue was successfully fixed: 
` overlayColor:MaterialStateProperty.all<Color>(Colors.transparent),`

**Comment by railson-ferreira** [comment]
The MaterialStateProperty is currently deprecated:
https://api.flutter.dev/flutter/material/MaterialStateProperty.html

Version 3.x of this package works only on Flutter >=3.19

For Flutter <=3.16 please use the version 2.x of this package.

I'll remember to set Flutter constraints properly next time.

**Comment by xykadra** [comment]
My current flutter version is: 3.19.5

**Comment by railson-ferreira** [comment]
I thought WidgetStateProperty was released in version 3.19.0, but it wasn't actually.

I have just fixed the constraints and published a new version.

I'm closing this issue now. If you encounter the problem again or have further questions, please feel free to reopen it.
