### ISSUE TITLE
itemposition bug

### ISSUE THREAD

**Issue by berslen** [railson-ferreira/scrollable_list_tab_scroller#16]
`
        final categoryServices = {
          "Category A": [
            "Item 1 (A)",
            "Item 2 (A)",
            "Item 3 (A)",
            "Item 4 (A)",
          ],
          "Category B": [
            "Item 1 (B)",
            "Item 2 (B)",
          ],
          "Category C": [
            "Item 1 (C)",
            "Item 2 (C)",
            "Item 3 (C)",
            "Item 4 (C)",
            "Item 5 (C)",
          ],
          "Category D": [
            "Item 1 (D)",
            "Item 2 (D)",
            "Item 3 (D)",
            "Item 4 (D)",
            "Item 5 (D)",
            "Item 6 (D)",
            "Item 7 (D)",
            "Item 8 (D)",
            "Item 9 (D)",
          ],
        };
        return ScrollableListTabScroller(
          itemCount: categoryServices.length,
          tabBuilder: (BuildContext context, int index, bool active) => Padding(
            padding: const EdgeInsets.symmetric(horizontal: 10),
            child: Text(
              categoryServices.keys.elementAt(index),
              style: !active
                  ? null
                  : const TextStyle(
                      fontWeight: FontWeight.bold,
                      color: Colors.green,
                    ),
            ),
          ),
          itemBuilder: (BuildContext context, int index) => Column(
            children: [
              Text(
                categoryServices.keys.elementAt(index),
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20),
              ),
              ...categoryServices.values
                  .elementAt(index)
                  .asMap()
                  .map(
                    (index, value) => MapEntry(
                      index,
                      ListTile(
                        leading: Container(
                          height: 40,
                          width: 40,
                          decoration: const BoxDecoration(
                            shape: BoxShape.circle,
                            color: Colors.grey,
                          ),
                          alignment: Alignment.center,
                          child: Text(index.toString()),
                        ),
                        title: Text(value),
                      ),
                    ),
                  )
                  .values,
            ],
          ),
        );
    
`

this code throws 
<img width="294" alt="image" src="https://github.com/user-attachments/assets/8b9a6f74-79e6-4d02-9403-db85bae77fce">

The relevant error-causing widget was:
    ScrollableListTabScroller ScrollableListTabScroller:/lib/features/partner/presentation/ui/custom/widgets/services_tab_content.dart:70:16
scrollable_positioned_list.dart:330

**Comment by railson-ferreira** [comment]
Can you provide more information?
- The result of the command `flutter pub deps`?
- Content of the line `services_tab_content.dart:70:16`

**Comment by berslen** [comment]
`
class ServicesTabContent extends SubView<PartnerController> {
  ServicesTabContent({super.key});

  @override
  Widget buildView(BuildContext context, PartnerController controller) {
    return BlocBuilder<PartnerCubit, PartnerState>(
      buildWhen: (previous, current) {
        return current is PageInitial ||
            current is PageLoading ||
            current is ServicesUpdated;
      },
      builder: (context, state) {
        if (state is PageInitial) {
          return Container();
        }
        if (state is PageLoading) {
          return const Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Center(
                child: CircularProgressIndicator(),
              ),
            ],
          );
        }
        final cubit = context.read<PartnerCubit>();

        final categoryServices = state is ServicesUpdated
            ? state.categoryServices
            : cubit.categoryServices;

        return ScrollableListTabScroller(
          itemCount: categoryServices.length,
          tabBuilder: (BuildContext context, int index, bool active) => Padding(
            padding: const EdgeInsets.symmetric(horizontal: 10),
            child: Text(
              categoryServices.keys.elementAt(index).name,
              style: !active
                  ? null
                  : const TextStyle(
                      fontWeight: FontWeight.bold,
                      color: Colors.green,
                    ),
            ),
          ),
          itemBuilder: (BuildContext context, int index) => Column(
            children: [
              Text(
                categoryServices.keys.elementAt(index).name,
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20),
              ),
              ...categoryServices.values
                  .elementAt(index)
                  .asMap()
                  .map(
                    (index, value) => MapEntry(
                      index,
                      ListTile(
                        leading: Container(
                          height: 40,
                          width: 40,
                          decoration: const BoxDecoration(
                            shape: BoxShape.circle,
                            color: Colors.grey,
                          ),
                          alignment: Alignment.center,
                          child: Text(index.toString()),
                        ),
                        title: Text(value.name),
                      ),
                    ),
                  )
                  .values,
            ],
          ),
        );
      },
    );
  }
}`



`
Dart SDK 3.4.3
Flutter SDK 3.22.2
goresy_mobile 1.0.0+1
├── adaptive_theme 3.6.0
│   ├── flutter...
│   └── shared_preferences...
├── android_path_provider 0.3.0
│   └── flutter...
├── async 2.11.0
│   ├── collection...
│   └── meta...
├── azure_application_insights 4.0.1
│   ├── stack_trace 1.11.1
│   │   └── path...
│   ├── crypto...
│   ├── http...
│   ├── logging...
│   └── meta...
├── build_runner 2.4.11
│   ├── analyzer 6.4.1
│   │   ├── _fe_analyzer_shared 67.0.0
│   │   │   └── meta...
│   │   ├── convert 3.1.1
│   │   │   └── typed_data...
│   │   ├── collection...
│   │   ├── crypto...
│   │   ├── glob...
│   │   ├── meta...
│   │   ├── package_config...
│   │   ├── path...
│   │   ├── pub_semver...
│   │   ├── source_span...
│   │   ├── watcher...
│   │   └── yaml...
│   ├── build 2.4.1
│   │   ├── analyzer...
│   │   ├── async...
│   │   ├── convert...
│   │   ├── crypto...
│   │   ├── glob...
│   │   ├── logging...
│   │   ├── meta...
│   │   ├── package_config...
│   │   └── path...
│   ├── build_config 1.1.1
│   │   ├── checked_yaml 2.0.3
│   │   │   ├── json_annotation...
│   │   │   ├── source_span...
│   │   │   └── yaml...
│   │   ├── json_annotation...
│   │   ├── path...
│   │   ├── pubspec_parse...
│   │   └── yaml...
│   ├── build_daemon 4.0.2
│   │   ├── built_collection 5.1.1
│   │   ├── built_value 8.9.2
│   │   │   ├── built_collection...
│   │   │   ├── collection...
│   │   │   ├── fixnum...
│   │   │   └── meta...
│   │   ├── crypto...
│   │   ├── http_multi_server...
│   │   ├── logging...
│   │   ├── path...
│   │   ├── pool...
│   │   ├── shelf...
│   │   ├── shelf_web_socket...
│   │   ├── stream_transform...
│   │   ├── watcher...
│   │   └── web_socket_channel...
│   ├── build_resolvers 2.4.2
│   │   ├── analyzer...
│   │   ├── async...
│   │   ├── build...
│   │   ├── collection...
│   │   ├── convert...
│   │   ├── crypto...
│   │   ├── graphs...
│   │   ├── logging...
│   │   ├── package_config...
│   │   ├── path...
│   │   ├── pool...
│   │   ├── pub_semver...
│   │   ├── stream_transform...
│   │   └── yaml...
│   ├── build_runner_core 7.3.1
│   │   ├── async...
│   │   ├── build...
│   │   ├── build_config...
│   │   ├── build_resolvers...
│   │   ├── collection...
│   │   ├── convert...
│   │   ├── crypto...
│   │   ├── glob...
│   │   ├── graphs...
│   │   ├── json_annotation...
│   │   ├── logging...
│   │   ├── meta...
│   │   ├── package_config...
│   │   ├── path...
│   │   ├── pool...
│   │   ├── timing...
│   │   ├── watcher...
│   │   └── yaml...
│   ├── code_builder 4.10.0
│   │   ├── built_collection...
│   │   ├── built_value...
│   │   ├── collection...
│   │   ├── matcher...
│   │   └── meta...
│   ├── dart_style 2.3.6
│   │   ├── analyzer...
│   │   ├── args...
│   │   ├── collection...
│   │   ├── path...
│   │   ├── pub_semver...
│   │   └── source_span...
│   ├── frontend_server_client 4.0.0
│   │   ├── async...
│   │   └── path...
│   ├── glob 2.1.2
│   │   ├── async...
│   │   ├── collection...
│   │   ├── file...
│   │   ├── path...
│   │   └── string_scanner...
│   ├── graphs 2.3.2
│   │   └── collection...
│   ├── http_multi_server 3.2.1
│   │   └── async...
│   ├── io 1.0.4
│   │   ├── meta...
│   │   ├── path...
│   │   └── string_scanner...
│   ├── js 0.6.7
│   │   └── meta...
│   ├── mime 1.0.5
│   ├── package_config 2.1.0
│   │   └── path...
│   ├── pool 1.5.1
│   │   ├── async...
│   │   └── stack_trace...
│   ├── pub_semver 2.1.4
│   │   ├── collection...
│   │   └── meta...
│   ├── pubspec_parse 1.3.0
│   │   ├── checked_yaml...
│   │   ├── collection...
│   │   ├── json_annotation...
│   │   ├── pub_semver...
│   │   └── yaml...
│   ├── shelf 1.4.1
│   │   ├── async...
│   │   ├── collection...
│   │   ├── http_parser...
│   │   ├── path...
│   │   ├── stack_trace...
│   │   └── stream_channel...
│   ├── shelf_web_socket 2.0.0
│   │   ├── shelf...
│   │   ├── stream_channel...
│   │   └── web_socket_channel...
│   ├── stream_transform 2.1.0
│   ├── timing 1.0.1
│   │   └── json_annotation...
│   ├── watcher 1.1.0
│   │   ├── async...
│   │   └── path...
│   ├── web_socket_channel 3.0.1
│   │   ├── web_socket 0.1.6
│   │   │   └── web...
│   │   ├── async...
│   │   ├── crypto...
│   │   ├── stream_channel...
│   │   └── web...
│   ├── yaml 3.1.2
│   │   ├── collection...
│   │   ├── source_span...
│   │   └── string_scanner...
│   ├── args...
│   ├── async...
│   ├── collection...
│   ├── crypto...
│   ├── logging...
│   ├── meta...
│   ├── path...
│   └── stack_trace...
├── cached_network_image 3.3.1
│   ├── cached_network_image_platform_interface 4.0.0
│   │   ├── flutter...
│   │   └── flutter_cache_manager...
│   ├── cached_network_image_web 1.2.0
│   │   ├── cached_network_image_platform_interface...
│   │   ├── flutter...
│   │   └── flutter_cache_manager...
│   ├── flutter_cache_manager 3.3.2
│   │   ├── rxdart 0.27.7
│   │   ├── sqflite 2.3.3+1
│   │   │   ├── sqflite_common 2.5.4
│   │   │   │   ├── synchronized 3.1.0+1
│   │   │   │   ├── meta...
│   │   │   │   └── path...
│   │   │   ├── flutter...
│   │   │   └── path...
│   │   ├── clock...
│   │   ├── collection...
│   │   ├── file...
│   │   ├── flutter...
│   │   ├── http...
│   │   ├── path...
│   │   ├── path_provider...
│   │   └── uuid...
│   ├── octo_image 2.0.0
│   │   └── flutter...
│   └── flutter...
├── country_flags 3.0.0
│   ├── jovial_svg 1.1.21
│   │   ├── jovial_misc 0.8.5
│   │   │   ├── pointycastle 3.9.1
│   │   │   │   ├── collection...
│   │   │   │   ├── convert...
│   │   │   │   └── js...
│   │   │   ├── async...
│   │   │   ├── collection...
│   │   │   ├── convert...
│   │   │   └── meta...
│   │   ├── args...
│   │   ├── collection...
│   │   ├── flutter...
│   │   ├── http...
│   │   ├── meta...
│   │   ├── vector_math...
│   │   └── xml...
│   ├── collection...
│   └── flutter...
├── darq 2.0.0
├── device_info_plus 10.1.0
│   ├── device_info_plus_platform_interface 7.0.0
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── ffi 2.1.2
│   ├── file 7.0.0
│   │   ├── meta...
│   │   └── path...
│   ├── flutter_web_plugins 0.0.0
│   │   ├── characters...
│   │   ├── collection...
│   │   ├── flutter...
│   │   ├── material_color_utilities...
│   │   ├── meta...
│   │   └── vector_math...
│   ├── web 0.5.1
│   ├── win32 5.5.1
│   │   └── ffi...
│   ├── win32_registry 1.1.3
│   │   ├── ffi...
│   │   └── win32...
│   ├── flutter...
│   └── meta...
├── dio 5.5.0+1
│   ├── dio_web_adapter 1.0.1
│   │   ├── dio...
│   │   ├── http_parser...
│   │   └── meta...
│   ├── http_parser 4.0.2
│   │   ├── typed_data 1.3.2
│   │   │   └── collection...
│   │   ├── collection...
│   │   ├── source_span...
│   │   └── string_scanner...
│   ├── path 1.9.0
│   ├── async...
│   └── meta...
├── dio_http2_adapter 2.5.3
│   ├── http2 2.3.0
│   ├── dio...
│   └── meta...
├── dio_smart_retry 6.0.0
│   ├── dio...
│   ├── http_parser...
│   └── path...
├── easy_localization 3.0.7
│   ├── args 2.5.0
│   ├── flutter_localizations 0.0.0
│   │   ├── characters...
│   │   ├── clock...
│   │   ├── collection...
│   │   ├── flutter...
│   │   ├── intl...
│   │   ├── material_color_utilities...
│   │   ├── meta...
│   │   ├── path...
│   │   └── vector_math...
│   ├── shared_preferences 2.2.3
│   │   ├── shared_preferences_android 2.2.3
│   │   │   ├── flutter...
│   │   │   └── shared_preferences_platform_interface...
│   │   ├── shared_preferences_foundation 2.4.0
│   │   │   ├── flutter...
│   │   │   └── shared_preferences_platform_interface...
│   │   ├── shared_preferences_linux 2.3.2
│   │   │   ├── file...
│   │   │   ├── flutter...
│   │   │   ├── path...
│   │   │   ├── path_provider_linux...
│   │   │   ├── path_provider_platform_interface...
│   │   │   └── shared_preferences_platform_interface...
│   │   ├── shared_preferences_platform_interface 2.4.0
│   │   │   ├── flutter...
│   │   │   └── plugin_platform_interface...
│   │   ├── shared_preferences_web 2.3.0
│   │   │   ├── flutter...
│   │   │   ├── flutter_web_plugins...
│   │   │   ├── shared_preferences_platform_interface...
│   │   │   └── web...
│   │   ├── shared_preferences_windows 2.3.2
│   │   │   ├── file...
│   │   │   ├── flutter...
│   │   │   ├── path...
│   │   │   ├── path_provider_platform_interface...
│   │   │   ├── path_provider_windows...
│   │   │   └── shared_preferences_platform_interface...
│   │   └── flutter...
│   ├── easy_logger...
│   ├── flutter...
│   ├── intl...
│   └── path...
├── easy_logger 0.0.2
│   └── flutter...
├── equatable 2.0.5
│   ├── collection...
│   └── meta...
├── extended_sliver 2.1.3
│   └── flutter...
├── file_picker 8.0.6
│   ├── cross_file 0.3.4+1
│   │   ├── meta...
│   │   └── web...
│   ├── flutter_plugin_android_lifecycle 2.0.20
│   │   └── flutter...
│   ├── plugin_platform_interface 2.1.8
│   │   └── meta...
│   ├── ffi...
│   ├── flutter...
│   ├── flutter_web_plugins...
│   ├── path...
│   ├── web...
│   └── win32...
├── fluro 2.0.5
│   └── flutter...
├── flutter 0.0.0
│   ├── characters 1.3.0
│   ├── collection 1.18.0
│   ├── material_color_utilities 0.8.0
│   │   └── collection...
│   ├── meta 1.12.0
│   ├── sky_engine 0.0.99
│   └── vector_math 2.1.4
├── flutter_bloc 8.1.6
│   ├── bloc 8.1.4
│   │   └── meta...
│   ├── provider 6.1.2
│   │   ├── nested 1.0.0
│   │   │   └── flutter...
│   │   ├── collection...
│   │   └── flutter...
│   └── flutter...
├── flutter_carousel_widget 2.2.0
│   └── flutter...
├── flutter_easyloading 3.0.5
│   ├── flutter_spinkit 5.2.1
│   │   └── flutter...
│   └── flutter...
├── flutter_form_builder 9.3.0
│   ├── flutter...
│   └── intl...
├── flutter_lints 4.0.0
│   └── lints 4.0.0
├── flutter_rating_bar 4.0.1
│   └── flutter...
├── flutter_secure_storage 9.2.2
│   ├── flutter_secure_storage_linux 1.2.1
│   │   ├── flutter...
│   │   └── flutter_secure_storage_platform_interface...
│   ├── flutter_secure_storage_macos 3.1.2
│   │   ├── flutter...
│   │   └── flutter_secure_storage_platform_interface...
│   ├── flutter_secure_storage_platform_interface 1.1.2
│   │   ├── flutter...
│   │   └── plugin_platform_interface...
│   ├── flutter_secure_storage_web 1.2.1
│   │   ├── flutter...
│   │   ├── flutter_secure_storage_platform_interface...
│   │   ├── flutter_web_plugins...
│   │   └── js...
│   ├── flutter_secure_storage_windows 3.1.2
│   │   ├── ffi...
│   │   ├── flutter...
│   │   ├── flutter_secure_storage_platform_interface...
│   │   ├── path...
│   │   ├── path_provider...
│   │   └── win32...
│   ├── flutter...
│   └── meta...
├── flutter_svg 2.0.10+1
│   ├── vector_graphics 1.1.11+1
│   │   ├── flutter...
│   │   ├── http...
│   │   └── vector_graphics_codec...
│   ├── vector_graphics_codec 1.1.11+1
│   ├── vector_graphics_compiler 1.1.11+1
│   │   ├── path_parsing 1.0.1
│   │   │   ├── meta...
│   │   │   └── vector_math...
│   │   ├── xml 6.5.0
│   │   │   ├── petitparser 6.0.2
│   │   │   │   └── meta...
│   │   │   ├── collection...
│   │   │   └── meta...
│   │   ├── args...
│   │   ├── meta...
│   │   ├── path...
│   │   └── vector_graphics_codec...
│   ├── flutter...
│   └── http...
├── flutter_test 0.0.0
│   ├── boolean_selector 2.1.1
│   │   ├── source_span...
│   │   └── string_scanner...
│   ├── fake_async 1.3.1
│   │   ├── clock...
│   │   └── collection...
│   ├── leak_tracker 10.0.4
│   │   ├── clock...
│   │   ├── collection...
│   │   ├── meta...
│   │   ├── path...
│   │   └── vm_service...
│   ├── leak_tracker_flutter_testing 3.0.3
│   │   ├── flutter...
│   │   ├── leak_tracker...
│   │   ├── leak_tracker_testing...
│   │   ├── matcher...
│   │   └── meta...
│   ├── leak_tracker_testing 3.0.1
│   │   ├── leak_tracker...
│   │   ├── matcher...
│   │   └── meta...
│   ├── matcher 0.12.16+1
│   │   ├── async...
│   │   ├── meta...
│   │   ├── stack_trace...
│   │   ├── term_glyph...
│   │   └── test_api...
│   ├── source_span 1.10.0
│   │   ├── collection...
│   │   ├── path...
│   │   └── term_glyph...
│   ├── stream_channel 2.1.2
│   │   └── async...
│   ├── string_scanner 1.2.0
│   │   └── source_span...
│   ├── term_glyph 1.2.1
│   ├── test_api 0.7.0
│   │   ├── async...
│   │   ├── boolean_selector...
│   │   ├── collection...
│   │   ├── meta...
│   │   ├── source_span...
│   │   ├── stack_trace...
│   │   ├── stream_channel...
│   │   ├── string_scanner...
│   │   └── term_glyph...
│   ├── vm_service 14.2.1
│   ├── async...
│   ├── characters...
│   ├── clock...
│   ├── collection...
│   ├── flutter...
│   ├── material_color_utilities...
│   ├── meta...
│   ├── path...
│   ├── stack_trace...
│   └── vector_math...
├── font_awesome_flutter 10.7.0
│   └── flutter...
├── form_builder_phone_field 2.0.1
│   ├── country_pickers 2.0.0
│   │   └── flutter...
│   ├── phone_number 2.1.0
│   │   ├── flutter...
│   │   └── meta...
│   ├── flutter...
│   └── flutter_form_builder...
├── form_builder_validators 11.0.0
│   ├── flutter...
│   ├── flutter_localizations...
│   └── intl...
├── get_it 7.7.0
│   ├── async...
│   ├── collection...
│   └── meta...
├── google_fonts 6.2.1
│   ├── crypto...
│   ├── flutter...
│   ├── http...
│   └── path_provider...
├── hive 2.2.3
│   ├── crypto 3.0.3
│   │   └── typed_data...
│   └── meta...
├── http 1.2.2
│   ├── async...
│   ├── http_parser...
│   ├── meta...
│   └── web...
├── internet_connection_checker_plus 2.5.0
│   ├── connectivity_plus 6.0.3
│   │   ├── connectivity_plus_platform_interface 2.0.0
│   │   │   ├── flutter...
│   │   │   ├── meta...
│   │   │   └── plugin_platform_interface...
│   │   ├── nm 0.5.0
│   │   │   └── dbus 0.7.10
│   │   │       ├── args...
│   │   │       ├── ffi...
│   │   │       ├── meta...
│   │   │       └── xml...
│   │   ├── collection...
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   ├── meta...
│   │   └── web...
│   ├── flutter...
│   └── http...
├── intl 0.19.0
│   ├── clock...
│   ├── meta...
│   └── path...
├── intl_phone_field 3.2.0
│   └── flutter...
├── jiffy 6.3.1
│   └── intl...
├── json_annotation 4.9.0
│   └── meta...
├── json_serializable 6.8.0
│   ├── source_gen 1.5.0
│   │   ├── analyzer...
│   │   ├── async...
│   │   ├── build...
│   │   ├── dart_style...
│   │   ├── glob...
│   │   ├── path...
│   │   ├── source_span...
│   │   └── yaml...
│   ├── source_helper 1.3.4
│   │   ├── analyzer...
│   │   ├── collection...
│   │   └── source_gen...
│   ├── analyzer...
│   ├── async...
│   ├── build...
│   ├── build_config...
│   ├── collection...
│   ├── json_annotation...
│   ├── meta...
│   ├── path...
│   ├── pub_semver...
│   └── pubspec_parse...
├── json_theme 6.5.0+1
│   ├── json_class 3.0.0+16
│   │   ├── intl...
│   │   ├── logging...
│   │   └── meta...
│   ├── json_schema 5.1.7
│   │   ├── rfc_6901 0.2.0
│   │   ├── uri 1.0.0
│   │   │   ├── quiver 3.2.1
│   │   │   │   └── matcher...
│   │   │   └── matcher...
│   │   ├── collection...
│   │   ├── http...
│   │   └── logging...
│   ├── json_theme_annotation 1.0.3+10
│   ├── logging 1.2.0
│   ├── flutter...
│   └── meta...
├── logger 2.4.0
├── oauth2 2.0.2
│   ├── collection...
│   ├── crypto...
│   ├── http...
│   └── http_parser...
├── package_info_plus 8.0.0
│   ├── clock 1.1.1
│   ├── package_info_plus_platform_interface 3.0.0
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── ffi...
│   ├── flutter...
│   ├── flutter_web_plugins...
│   ├── http...
│   ├── meta...
│   ├── path...
│   ├── web...
│   └── win32...
├── path_provider 2.1.3
│   ├── path_provider_android 2.2.7
│   │   ├── flutter...
│   │   └── path_provider_platform_interface...
│   ├── path_provider_foundation 2.4.0
│   │   ├── flutter...
│   │   └── path_provider_platform_interface...
│   ├── path_provider_linux 2.2.1
│   │   ├── xdg_directories 1.0.4
│   │   │   ├── meta...
│   │   │   └── path...
│   │   ├── ffi...
│   │   ├── flutter...
│   │   ├── path...
│   │   └── path_provider_platform_interface...
│   ├── path_provider_platform_interface 2.1.2
│   │   ├── platform 3.1.5
│   │   ├── flutter...
│   │   └── plugin_platform_interface...
│   ├── path_provider_windows 2.3.0
│   │   ├── ffi...
│   │   ├── flutter...
│   │   ├── path...
│   │   └── path_provider_platform_interface...
│   └── flutter...
├── permission_handler 11.3.1
│   ├── permission_handler_android 12.0.7
│   │   ├── flutter...
│   │   └── permission_handler_platform_interface...
│   ├── permission_handler_apple 9.4.5
│   │   ├── flutter...
│   │   └── permission_handler_platform_interface...
│   ├── permission_handler_html 0.1.1
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   └── permission_handler_platform_interface...
│   ├── permission_handler_platform_interface 4.2.1
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── permission_handler_windows 0.2.1
│   │   ├── flutter...
│   │   └── permission_handler_platform_interface...
│   ├── flutter...
│   └── meta...
├── readmore 3.0.0
│   └── flutter...
├── scrollable_list_tab_scroller 3.0.1
│   ├── scrollable_positioned_list 0.3.8
│   │   ├── collection...
│   │   └── flutter...
│   ├── scrolls_to_top 2.1.1
│   │   └── flutter...
│   └── flutter...
├── sliding_sheet2 2.0.1
│   └── flutter...
├── styled_text 8.1.0
│   ├── xmlstream 1.1.1
│   └── flutter...
├── url_launcher 6.3.0
│   ├── url_launcher_android 6.3.5
│   │   ├── flutter...
│   │   └── url_launcher_platform_interface...
│   ├── url_launcher_ios 6.3.1
│   │   ├── flutter...
│   │   └── url_launcher_platform_interface...
│   ├── url_launcher_linux 3.1.1
│   │   ├── flutter...
│   │   └── url_launcher_platform_interface...
│   ├── url_launcher_macos 3.2.0
│   │   ├── flutter...
│   │   └── url_launcher_platform_interface...
│   ├── url_launcher_platform_interface 2.3.2
│   │   ├── flutter...
│   │   └── plugin_platform_interface...
│   ├── url_launcher_web 2.3.1
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   ├── url_launcher_platform_interface...
│   │   └── web...
│   ├── url_launcher_windows 3.1.1
│   │   ├── flutter...
│   │   └── url_launcher_platform_interface...
│   └── flutter...
├── uuid 4.4.2
│   ├── fixnum 1.1.0
│   ├── sprintf 7.0.0
│   ├── crypto...
│   └── meta...
└── visibility_aware_state 1.0.5
    └── flutter...
`

**Comment by railson-ferreira** [comment]
Seems that it is not an issue related to this package, I wanted to see the exact line that caused that error in order to be sure and try to help you solving it. Please provide only the line `70` from the file `services_tab_content.dart`.

**Comment by berslen** [comment]
changed the code little bit so new code is

```
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:scrollable_list_tab_scroller/scrollable_list_tab_scroller.dart';

import '../../../../../../stack/base/presentation/sub_view.dart';
import '../../../blocs/partner_cubit.dart';
import '../../controllers/partner_controller.dart';

class ServicesTabContent extends SubView<PartnerController> {
  ServicesTabContent({super.key});

  @override
  Widget buildView(BuildContext context, PartnerController controller) {
    return BlocBuilder<PartnerCubit, PartnerState>(
      buildWhen: (previous, current) {
        return current is PageInitial ||
            current is PageLoading ||
            current is ServicesUpdated;
      },
      builder: (context, state) {
        if (state is PageInitial) {
          return Container();
        }
        if (state is PageLoading) {
          return const Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Center(
                child: CircularProgressIndicator(),
              ),
            ],
          );
        }
        final cubit = context.read<PartnerCubit>();

        final categoryServices = state is ServicesUpdated
            ? state.categoryServices
            : cubit.categoryServices;

        return ScrollableListTabScroller(
          itemCount: categoryServices.length,
          tabBuilder: (BuildContext context, int index, bool active) => Padding(
            padding: const EdgeInsets.symmetric(horizontal: 10),
            child: Text(
              categoryServices.keys.elementAt(index).name,
              style: !active
                  ? null
                  : const TextStyle(
                      fontWeight: FontWeight.bold,
                      color: Colors.green,
                    ),
            ),
          ),
          itemBuilder: (BuildContext context, int index) => Column(
            children: [
              Text(
                categoryServices.keys.elementAt(index).name,
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20),
              ),
              ...categoryServices.values
                  .elementAt(index)
                  .asMap()
                  .map(
                    (index, value) => MapEntry(
                      index,
                      ListTile(
                        leading: Text(
                          index.toString(),
                        ),
                        title: Text(value.name),
                      ),
                    ),
                  )
                  .values,
            ],
          ),
        );
      },
    );
  }
}

```


Thrown error 
```

════════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building ScrollsToTop(dependencies: [PrimaryScrollController], state: _ScrollsToTopState#213da):
type 'double' is not a subtype of type 'ItemPosition?'

The relevant error-causing widget was:
    ScrollableListTabScroller ScrollableListTabScroller:file:///Users/berslenakkaya/Desktop/goresy_mobile/lib/features/partner/presentation/ui/custom/widgets/services_tab_content.dart:40:16

When the exception was thrown, this was the stack:
#0      _ScrollablePositionedListState.initState (package:scrollable_positioned_list/src/scrollable_positioned_list.dart:330:19)
scrollable_positioned_list.dart:330
```


40th line is return ScrollableListTabScroller(


scrollable_positioned_list.dart:330 is     ItemPosition? initialPosition = PageStorage.of(context).readState(context);

**Comment by railson-ferreira** [comment]
It is an issue on `scrollable_positioned_list` package.

Here is a suggestion that will likely solve that error:
https://github.com/google/flutter.widgets/issues/266#issuecomment-900684705

Since it is not an issue on `scrollable_list_tab_scroller`, I am closing it now.

**Comment by berslen** [comment]
yeap seems to fix the problem. thanks for your help
