### ISSUE TITLE
tab not highlight and message show

### ISSUE THREAD

**Issue by nikunjshaligram** [railson-ferreira/scrollable_list_tab_scroller#19]
This is my tab bar code :

Widget _buildTabBarWithList(BuildContext context) => Theme(
        data: Theme.of(context).copyWith(
          tabBarTheme: Theme.of(context).tabBarTheme.copyWith(dividerHeight: 0),
        ),
        child: ScrollableListTabScroller(
          itemCount: controller.deliveriesfinalList.length,
          headerContainerBuilder: (_, child) => Container(
            color: AppColors.statusBarColor,
            child: Container(
              height: 8.screenHeight,
              color: AppColors.statusBarColor,
              child: Container(
                height: 4.5.screenHeight,
                padding: EdgeInsets.symmetric(
                  horizontal: 0.5.screenWidth,
                  vertical: 0.7.screenHeight,
                ),
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(50),
                  color: AppColors.whiteColor,
                ),
                child: child,
              ).paddingOnly(
                bottom: 1.screenHeight,
                left: 6.screenWidth,
                right: 6.screenWidth,
              ),
            ),
          ),
          tabBuilder: (context, index, active) => controller
                      .deliveriesfinalList[index].name! !=
                  'Delivered Deliveries'
              ? Container(
                  width: 41.screenWidth,
                  alignment: Alignment.center,
                  decoration: active
                      ? BoxDecoration(
                          gradient: AppBackground.getTabBarBackgroundGradient(),
                          borderRadius: BorderRadius.circular(50),
                          border: Border.all(
                            color: AppColors.darkOrangeColor,
                          ),
                        )
                      : BoxDecoration(
                          color: Colors
                              .transparent, // Ensures there's no background color
                          borderRadius: BorderRadius.circular(50),
                        ),
                  child: Text(
                    controller.deliveriesfinalList[index].name!,
                    style: !active
                        ? AppStyle.mediumTextStyle(
                            size: 10.sp,
                            color: AppColors.lightTextColor,
                          )
                        : AppStyle.semiBoldTextStyle(
                            size: 10.sp,
                            color: AppColors.primaryColor,
                          ),
                  ),
                ).paddingSymmetric(horizontal: 1.screenWidth)
              : const SizedBox(),
          itemBuilder: (context, index) => _buildDeliveryList(index),
        ),
      );
      
    If there is no data in list so at that time once i am click on tab so no tab highlight and not scroll.
    
    This is my tabbar list code :
    
    Widget _buildDeliveryList(int index) => controller
              .deliveriesfinalList[index].name! !=
          'Delivered Deliveries'
      ? ListView(
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          children: [
            Padding(
              padding: EdgeInsets.symmetric(
                horizontal: 2.screenHeight,
                vertical: 2.screenWidth,
              ),
              child: Row(
                children: [
                  Text(
                    '${controller.deliveriesfinalList[index].name!} (${controller.deliveriesfinalList[index].deliveries!.length})',
                    style: AppStyle.semiBoldTextStyle(
                      size: AppTextSizes.regular,
                      color: AppColors.lightTextColor,
                    ),
                  ),
                  const Spacer(),
                  if (controller.deliveriesfinalList[index].name! ==
                      "Today's Deliveries")
                    Obx(
                      () => Row(
                        children: [
                          CommonWidget().buildRegularText(
                            AppLabel.pickupAll,
                            AppTextSizes.tiny,
                            AppColors.lightTextColor,
                          ),
                          _buildCheckbox(
                            val: controller.pickedUpAll.value,
                            onChanged: (value) {
                              controller.pickedUpAllCheckBoxTap(
                                val: value!,
                              );
                            },
                          ),
                        ],
                      ),
                    ),
                ],
              ).paddingOnly(
                top: controller.deliveriesfinalList[index].name! ==
                        "Today's Deliveries"
                    ? 1.screenHeight
                    : 0.screenHeight,
              ),
            ),
            ...controller.deliveriesfinalList[index].deliveries!
                .asMap()
                .map(
                  (index1, delivery) => controller.deliveriesfinalList[index]
                              .deliveries![index1].deliveryStatus !=
                          'Delivered'
                      ? MapEntry(
                          index1,
                          GestureDetector(
                            onTap: () {
                              controller.deliveryItemTap(
                                controller.deliveriesfinalList[index]
                                    .deliveries![index1],
                              );
                            },
                            child: DecoratedBox(
                              decoration:
                                  CommonWidget().buildContainerCardDecoration(),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Row(
                                    mainAxisSize: MainAxisSize.min,
                                    children: [
                                      CommonWidget().buildDeliveryImage(
                                        controller.animationController!,
                                      ),
                                      2.screenWidth.width,
                                      Expanded(
                                        child: Column(
                                          crossAxisAlignment:
                                              CrossAxisAlignment.start,
                                          children: [
                                            _buildDeliveryTitle(
                                              delivery.name == null ||
                                                      delivery.name!.isEmpty ||
                                                      delivery.name == 'null'
                                                  ? ''
                                                  : delivery.name.toString(),
                                            ),
                                          ],
                                        ),
                                      ),
                                      Align(
                                        alignment: Alignment.centerRight,
                                        child: delivery.deliveryStatus ==
                                                    'Pending' ||
                                                delivery.deliveryStatus ==
                                                    'Unable to Deliver' ||
                                                delivery.deliveryStatus ==
                                                    'Unable To Deliver' ||
                                                delivery.deliveryStatus ==
                                                    'Partial Delivery'
                                            ? _buildCheckbox(
                                                val: delivery.isChecked!,
                                                onChanged: (value) {
                                                  controller
                                                      .checkBoxSelectionTap(
                                                    tabIndex: index,
                                                    deliveryIndex: index1,
                                                    value: value!,
                                                  );
                                                },
                                              )
                                            : const SizedBox(),
                                      ),
                                    ],
                                  ),
                                  _buildDeliveryDate(delivery.date),
                                  _buildDeliveryAddress(delivery.contact!),
                                  Row(
                                    children: [
                                      _buildDeliveryStatusText(
                                        AppLabel.deliveryStatus,
                                      ),
                                      1.screenWidth.width,
                                      Container(
                                        padding: EdgeInsets.symmetric(
                                          horizontal: 2.screenWidth,
                                          vertical: 0.5.screenHeight,
                                        ),
                                        decoration: CommonWidget()
                                            .buildDeliveryStatusDecoration(
                                          delivery.deliveryStatus.toString(),
                                          // StatusEnum.fromInt(delivery.state!)
                                          //     .displayName,
                                        ),
                                        child:
                                            CommonWidget().buildDeliveryStatus(
                                          delivery.deliveryStatus.toString(),
                                          // StatusEnum.fromInt(delivery.state!)
                                          //     .displayName,
                                        ),
                                      ),
                                    ],
                                  ).paddingOnly(
                                    left: 12.screenWidth,
                                    bottom: 0.5.screenHeight,
                                  ),
                                  Row(
                                    mainAxisAlignment: MainAxisAlignment.end,
                                    children: [
                                      _buildParcelText(),
                                      _buildParcelQuantity(
                                        delivery.packages![0].podLines!.length,
                                      ),
                                    ],
                                  ).paddingOnly(top: 0.5.screenHeight),
                                ],
                              ).paddingOnly(
                                left: 2.screenWidth,
                                right: 2.screenWidth,
                                top: 1.screenHeight,
                                bottom: 1.screenHeight,
                              ),
                            ),
                          ).paddingSymmetric(
                            horizontal: 4.screenWidth,
                            vertical: 1.screenHeight,
                          ),
                        )
                      : MapEntry(
                          index1,
                          const SizedBox(),
                        ),
                )
                .values,
          ],
        )
      : const SizedBox();
    
    
    For this if there is no data on particular tab so how to show 'no data found' message with this code.

**Comment by railson-ferreira** [comment]
Seems that you are trying to do things that are beyond of the purpose of this package.

I will understand that as a feature request, but I could not understand your explanation.

If you wish to request a new feature, please detail and organize better the information in order to make it clear, and then open another issue with 'feature request' in the title.
