### ISSUE TITLE
Tab not highlight

### ISSUE THREAD

**Issue by nikunjshaligram** [railson-ferreira/scrollable_list_tab_scroller#20]
Widget _buildTabBarWithList(BuildContext context) => Theme(
        data: Theme.of(context).copyWith(
          tabBarTheme: Theme.of(context).tabBarTheme.copyWith(dividerHeight: 0),
        ),
        child: Obx(
          () => ScrollableListTabScroller(
            itemCount: controller.deliveriesfinalList.length,
            headerContainerBuilder: (_, child) => Container(
              color: AppColors.statusBarColor,
              child: Container(
                height: 8.screenHeight,
                color: AppColors.statusBarColor,
                child: Container(
                  height: 4.5.screenHeight,
                  padding: EdgeInsets.symmetric(
                    horizontal: 0.5.screenWidth,
                    vertical: 0.7.screenHeight,
                  ),
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(50),
                    color: AppColors.whiteColor,
                  ),
                  child: child,
                ).paddingOnly(
                  bottom: 1.screenHeight,
                  left: 6.screenWidth,
                  right: 6.screenWidth,
                ),
              ),
            ),
            tabBuilder: (context, index, active) => Obx(
              () => controller.deliveriesfinalList[index].name! !=
                      'Delivered Deliveries'
                  ? Container(
                      width: 41.screenWidth,
                      alignment: Alignment.center,
                      decoration: active
                          ? BoxDecoration(
                              gradient:
                                  AppBackground.getTabBarBackgroundGradient(),
                              borderRadius: BorderRadius.circular(50),
                              border: Border.all(
                                color: AppColors.darkOrangeColor,
                              ),
                            )
                          : BoxDecoration(
                              color: Colors
                                  .transparent, // Ensures there's no background color
                              borderRadius: BorderRadius.circular(50),
                            ),
                      child: Text(
                        controller.deliveriesfinalList[index].name!,
                        style: !active
                            ? AppStyle.mediumTextStyle(
                                size: 10.sp,
                                color: AppColors.lightTextColor,
                              )
                            : AppStyle.semiBoldTextStyle(
                                size: 10.sp,
                                color: AppColors.primaryColor,
                              ),
                      ),
                    ).paddingSymmetric(horizontal: 1.screenWidth)
                  : const SizedBox(),
            ),
            itemBuilder: (context, index) => _buildDeliveryList(index),
          ),
        ),
      );
      
This is my code, but the issue is if there is only 2 content or less content, the tab is not highlighted.

**Comment by railson-ferreira** [comment]
duplicate: #19
