### ISSUE TITLE
PrimaryScrollController.of() was called with a context that does not contain a PrimaryScrollController widget.

### ISSUE THREAD

**Issue by Obada2020** [railson-ferreira/scrollable_list_tab_scroller#4]
when i use ScrollableListTabScroller in CustomScrollView i get this issue

**Comment by Obada2020** [comment]
i solve this issue by add PrimaryScrollController above of ScrollableListTabScroller 👍

**Comment by faten-elsaeed** [comment]
could you provide code snippet for using ScrollableListTabScroller in CustomScrollView?
