### ISSUE TITLE
Unable to increase tab section height

### ISSUE THREAD

**Issue by enqvida** [railson-ferreira/scrollable_list_tab_scroller#6]
Hi, there seems to be an issue with customising tab section. Wrapping text with container and adding height or vertical padding has no effect.

**Comment by railson-ferreira** [comment]
Hello @enqvida 

Considering you are placing it in `tabBuilder`, it won't work.

It must be customized in `headerContainerBuilder`, this is the default one:
```dart
SizedBox(
    height: 30,
    child: child,
)
``` 

Suggestion:
```dart
headerContainerBuilder: (_, Widget child) {
    const customHeight = 100.0;
    return Container(
        height: customHeight,
        child: child,
    );
},
tabBuilder: (_, int index, bool active) {
    return Text(
        "Text $index",
        style: TextStyle(color: active ? Colors.green : Colors.red),
    );
}
```

**Comment by railson-ferreira** [comment]
It seems that the issue has been resolved based on the information provided. However, since there hasn't been any confirmation from the reporter, I'm closing this issue now. If you encounter the problem again or have further questions, please feel free to reopen it.

**Comment by enqvida** [comment]
Thanks for clarification :)

**Comment by nikunjshaligram** [comment]
I appreciate your help. The issue has been resolved.

**Comment by nikunjshaligram** [comment]
ScrollableListTabScroller(
                  itemCount: controller.deliveriesfinalList.length,
                  headerContainerBuilder: (_, child) => Container(
                    height: 8.screenHeight,
                    color: AppColors.statusBarColor,
                    child: Container(
                      height: 4.5.screenHeight,
                      padding: EdgeInsets.symmetric(
                        horizontal: 0.5.screenWidth,
                        vertical: 0.7.screenHeight,
                      ),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(50),
                        color: AppColors.whiteColor,
                      ),
                      child: child,
                    ).paddingOnly(
                      bottom: 1.screenHeight,
                      left: 6.screenWidth,
                      right: 6.screenWidth,
                    ),
                  ),
                  tabBuilder: (context, index, active) => Container(
                    width: 41.5.screenWidth,
                    alignment: Alignment.center,
                    decoration: active
                        ? BoxDecoration(
                            gradient:
                                AppBackground.getTabBarBackgroundGradient(),
                            borderRadius: BorderRadius.circular(50),
                            border: Border.all(
                              color: AppColors.darkOrangeColor,
                            ),
                          )
                        : BoxDecoration(
                            color: Colors
                                .transparent, // Ensures there's no background color
                            borderRadius: BorderRadius.circular(50),
                          ),
                    child: Text(
                      controller.deliveriesfinalList[index].name!,
                      style: !active
                          ? AppStyle.mediumTextStyle(
                              size: 11.sp,
                              color: AppColors.lightTextColor,
                            )
                          : AppStyle.semiBoldTextStyle(
                              size: 11.sp,
                              color: AppColors.primaryColor,
                            ),
                    ),
                  ).paddingSymmetric(horizontal: 1.screenWidth),
     ),
                  
I have a code snippet for a tab bar, but it's displaying a bottom border or divider. How can I remove it?

**Comment by railson-ferreira** [comment]
Please open another issue or discussion to talk about a different topic.
