### ISSUE TITLE
add package last version then pub get. success pub get but flutter run project show this error 

### ISSUE THREAD

**Issue by Babag3ldi** [railson-ferreira/scrollable_list_tab_scroller#9]
/C:/src/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/scrolls_to_top-2.1.1/lib/scrolls_to_top.dart:81:33: Error: Member not found: 'PrimaryScrollController.maybeOf'.
        PrimaryScrollController.maybeOf(Navigator.of(context).context) ??
                                ^^^^^^^
/C:/src/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/scrolls_to_top-2.1.1/lib/scrolls_to_top.dart:82:37: Error: Member not found: 'PrimaryScrollController.maybeOf'.
            PrimaryScrollController.maybeOf(context);
                                    ^^^^^^^
/C:/src/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/scrollable_positioned_list-0.3.8/lib/src/scrollable_positioned_list.dart:330:61: Error: Method 'readState' cannot be called on 'PageStorageBucket?' because it is potentially null.
- 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('/C:/src/flutter/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
page_storage.dart:1
Try calling using ?. instead.
    ItemPosition? initialPosition = PageStorage.of(context).readState(context);
                                                            ^^^^^^^^^
/C:/src/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/scrollable_positioned_list-0.3.8/lib/src/scrollable_positioned_list.dart:646:31: Error: Method 'writeState' cannot be called on 'PageStorageBucket?' because it is potentially null.
- 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('/C:/src/flutter/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
page_storage.dart:1
Try calling using ?. instead.
      PageStorage.of(context).writeState(
                              ^^^^^^^^^^
2

FAILURE: Build failed with an exception.
* Where:
Script 'C:\src\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

**Comment by railson-ferreira** [comment]
Hello @Babag3ldi
It seems that you are using an older version of Flutter. I recommend upgrading to at least Flutter 3.10.0 due to breaking changes related to Dart null safety.

You can force the use of an older version of this package and its dependencies. After some analysis, I could say that the following version may be the latest one you can use with older Flutter versions.
```
scrollable_list_tab_scroller: 1.1.1
scrollable_positioned_list: 0.3.5
scrolls_to_top: 2.0.0
```

**Comment by railson-ferreira** [comment]
Since there hasn't been any confirmation from the reporter, I'm closing this issue now. If you encounter the problem again or have further questions, please feel free to reopen it.

**Comment by Babag3ldi** [comment]
Hello railson-ferreira,

Thank you for your prompt response and valuable recommendations. I truly appreciate your insight into the potential compatibility issues and the suggested solutions. Your guidance on upgrading to Flutter version 3.7.0 and the specific package versions to maintain compatibility with older Flutter versions is immensely helpful.

Once again, thank you for your time and assistance. Your support is greatly appreciated.

Best regards,
Babag3ldi
